### ISSUE TITLE
running the code and syntax error

### ISSUE THREAD

**Issue by lizhengduo** [natashabatalha/picaso#228]
hello! i  use picaso to get a brown dwarf spectrum, and get error called "syntax error", and i don't know how to fix:     
  Traceback (most recent call last):
  File "/bdtest.py", line 73, in <module>
    df = bd.spectrum(opa, full_output=True)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/miniconda3/envs/xesmf_env/lib/python3.12/site-packages/picaso-3.3-py3.12.egg/picaso/justdoit.py", line 3731, in spectrum
    return picaso(self, opacityclass,dimension=dimension,calculation=calculation,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/miniconda3/envs/xesmf_env/lib/python3.12/site-packages/picaso-3.3-py3.12.egg/picaso/justdoit.py", line 228, in picaso
    get_opacities(atm,exclude_mol=exclude_mol)
  File "~/miniconda3/envs/xesmf_env/lib/python3.12/site-packages/picaso-3.3-py3.12.egg/picaso/optics.py", line 2604, in get_opacities_nearest
    data = self._get_query_molecular(ind_pt,molecules,cur)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/miniconda3/envs/xesmf_env/lib/python3.12/site-packages/picaso-3.3-py3.12.egg/picaso/optics.py", line 2492, in _get_query_molecular
    cur.execute("""SELECT molecule,ptid,opacity
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: near "(": syntax error

**Comment by lizhengduo** [comment]
this error fixed by gpt, it changed the optics.py _get_query_continuum and _get_query_molecular functions, just syntax error.
        if len(tcia) == 1:
            query_temp = "AND temperature = ?"
        else:
            query_temp = "AND temperature IN ({})".format(','.join(['?'] * len(tcia)))

        if len(cia_mol) == 1:
            query_mol = "WHERE molecule = ?"
        else:
            query_mol = "WHERE molecule IN ({})".format(','.join(['?'] * len(cia_mol)))


        query_params = tuple(cia_mol) + tuple(tcia)

        cur.execute("""
            SELECT molecule, temperature, opacity 
            FROM continuum 
            {} 
            {}
        """.format(query_mol, query_temp), query_params)
the same for _get_query_molecular.

**Comment by natashabatalha** [comment]
@lizhengduo would you like to submit a PR with your changes?

**Comment by natashabatalha** [comment]
Fixed in ck-newdev-merge #258 via commit #[87e24c3](https://github.com/natashabatalha/picaso/commit/87e24c364c8bf93a1117706e58bfc3dec9ea8fca)
